# Site settings
title: "Beomsu Park"
baseurl: "/site"
url: "https://qkrqjatn218.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Beomsu Park(범수 박)
  desc: Hello nice to meet you
  email: qkrqjatn218@gmail.com
  selfie: assets/img/IMG_3057.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: qkrqjatn218
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/qkrqjatn218/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
